"use client";

import { Download, Printer, QrCode } from "lucide-react";

import { useT } from "@/components/i18n/i18n-provider";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { interpolate } from "@/lib/i18n";

/**
 * One table's QR, big enough to read on screen.
 *
 * The SVG is rendered on the server and passed in as markup — the browser never
 * loads a QR library, which keeps the tables page light on a phone.
 */
export function QrPreview({
  tableId,
  tableNumber,
  url,
  svg,
}: {
  tableId: string;
  tableNumber: string;
  url: string;
  svg: string;
}) {
  const t = useT();

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="ghost" size="icon" aria-label={t.qr.show}>
          <QrCode className="size-4" />
        </Button>
      </DialogTrigger>

      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>
            {interpolate(t.qr.tableTitle, { number: tableNumber })}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div
            className="mx-auto w-48 [&>svg]:h-auto [&>svg]:w-full"
            // Server-generated by the `qrcode` package from our own URL.
            dangerouslySetInnerHTML={{ __html: svg }}
          />

          <p
            className="text-muted-foreground break-all text-center font-mono text-xs"
            dir="ltr"
          >
            {url}
          </p>

          <div className="flex justify-center gap-2">
            <Button asChild variant="outline" size="sm">
              <a href={`/api/tables/${tableId}/qr`} download>
                <Download />
                {t.qr.downloadPng}
              </a>
            </Button>
            <Button asChild variant="outline" size="sm">
              <a href={`/dashboard/tables/print?table=${tableId}`} target="_blank">
                <Printer />
                {t.qr.print}
              </a>
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
